{% set name = "pynomaly" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyNomaly-{{ version }}.tar.gz
  sha256: 90c5e3b58fa3dc144cdcb145afdecb212131e269a5be67173293e18acdd73c6f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}
    - python-utils

test:
  imports:
    - PyNomaly
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vc1492a/PyNomaly
  summary: 'A Python 3 implementation of LoOP: Local Outlier Probabilities.'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
