schema_version: 1

context:
  name: pynomaly
  version: 0.3.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 2e5f51b71e86c400d7331128d0e6f60ade3fd8d2393c8c7ebdb592387d84cb07

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - numpy
    - python >=${{ python_min }}
    - python-utils

tests:
  - python:
      imports:
        - PyNomaly
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: "A Python 3 implementation of LoOP: Local Outlier Probabilities."
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/vc1492a/PyNomaly

extra:
  recipe-maintainers:
    - thewchan
